# Generated by Django 2.1.4 on 2019-02-21 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductsImg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.BigIntegerField(default=0)),
                ('img', models.ImageField(blank=True, default='default_bulb.jpg', upload_to='')),
            ],
        ),
    ]
