# Generated by Django 2.1.4 on 2019-02-27 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produkty', '0002_auto_20190221_1714'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=30, unique=True)),
                ('jmeno', models.CharField(blank=True, max_length=250)),
                ('guide', models.CharField(blank=True, max_length=250)),
                ('shortDescription', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('vyrobce', models.CharField(max_length=30)),
                ('zasoby', models.BigIntegerField(default=0, null=True)),
                ('cena', models.BigIntegerField(default=100, null=True)),
            ],
        ),
    ]
