# Generated by Django 2.1.4 on 2019-03-09 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produkty', '0004_auto_20190309_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='cod',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='produkty.Product'),
        ),
    ]
